name: kohl
grade: stable
version: v0.2.0
base: core20

license: MIT

summary: Highlight Logs

description: >
  A pager that highlights logs.

confinement: strict

apps:
  kohl:
    command: bin/kohl

parts:
  kohl:
    source: .
    plugin: npm
    npm-node-version: 15.0.1
